# Generated by Django 4.2.30 on 2026-05-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('defenders', models.IntegerField(default=4)),
                ('midfielders', models.IntegerField(default=4)),
                ('forwards', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('rating', models.IntegerField(default=75)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('club', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, default='default_player.png', null=True, upload_to='players/')),
                ('pitch_x', models.FloatField(default=0.0)),
                ('pitch_y', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.formation')),
            ],
        ),
    ]
