# Generated by Django 4.2.30 on 2026-05-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='player',
            name='defending',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='dribbling',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.FloatField(default=1.8),
        ),
        migrations.AddField(
            model_name='player',
            name='pace',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='passing',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='physical',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(default='Diestro', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='shooting',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(default=75),
        ),
    ]
